id: PD3F918AD
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Tenpe Nyima Series
  language: de
  description: 'Texts by and about the Third Dodrupchen, Jigme Tenpe Nyima (rdo grub
    chen ''jigs med bstan pa''i nyi ma, 1865–1926):'
  volume:
    97e16225ca61455ba896e87ab28617b1:
      title: Advice for a Dying Practitioner
      parent: Advice
    4e5daade08d540acaadeed31fd915945:
      title: On Seeing the Guru as a Buddha
      parent: Advice
    d32bf3e694b14c2982c4058ae29d03a6:
      title: On Sleep
      parent: Advice
    e84594a8264a4da8a201d6b0876ca1bb:
      title: On the Ignorance of the Learned
      parent: Advice
    acaaaa28d93142a8b1988c283e1d4a16:
      title: Retreat Advice
      parent: Advice
    f54a1d4f2c1c4290bdb66e550e83dad5:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    972bdea67a5140739af1dea0ef496cab:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Advice
    7d474c4bb3894ec48d4d88501ea14d1f:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers
    cea91e9d129945c5b816dee6c849cd11:
      title: Aspirations in Accordance with the Dharma
      parent: Aspiration Prayers
    168c3499f271438abd9bba4b0f7463be:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    fe7580e536794bc59cff6cec612c9d5b:
      title: A Simple Visualization for the Seven-Line Prayer
      parent: Commentaries
    228451cf56e14d69a388fa53e3bba71d:
      title: 'Garland of Night-Blooming Water Lilies: A Commentary on the Guru Siddhi
        Mantra'
      parent: Commentaries
    f920a1a598e748768393f2f881e098bb:
      title: 'Lamp That Illuminates the Excellent Path of Great Bliss: A Guide to
        the Practice Text of the Female Awareness-Holder, the Queen of Great Bliss'
      parent: Commentaries
    95b78f2c6cbd4378a04710b8909a6c56:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    907bfe01e26543748c38304d729810c2:
      title: Teaching on the Offering of Flowers
      parent: Commentaries
    1d100fb7157f4a1a86be068fd77a3708:
      title: Advice for Hor Özer
      parent: Dzogchen
    e6cdd63a1ce24c3b9310b9bbdfb1f839:
      title: Advice for Palseng
      parent: Dzogchen
    a783badee21349678aa266997d7afd24:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Dzogchen
    c1033d120dfe423291048cf3fe50db77:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    898e6bfdb27a4c4999ca76f1947644c0:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    42c48504a4f4458784eab569b7f89e74:
      title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
      parent: Lineage Prayers
    d620196eb43441cf9aa5be1d84935d4f:
      title: A Brief Ritual for Consecrating Representations of Enlightened Body,
        Speech and Mind
      parent: Practices
    3385179626bf402d8595148c770fe5b9:
      title: Rigdzin Düpa Amṛta Offering
      parent: Practices
    8c5b87139872471f92da44a2947a0760:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Practices
    cf5335290bb2472ea093e162522bf67f:
      title: Yumka Fulfilment Practice
      parent: Practices
    cafa9265e86b42628e01a3af9262da1e:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    b1ab703e1cc544b5b5c755d2ce77a1e5:
      title: In Praise of Sönam Palge
      parent: Praise
    125917cd98f14542ad8ea88e2a5ca4f4:
      title: Prayer to Ārya Tārā
      parent: Prayers
    67d1dfa1358e4ddeb56af95cc9c21b22:
      title: Prayer to Avalokiteśvara
      parent: Prayers
    bf068f1d7f844d16ab8b79084f12555f:
      title: Prayer to Buddha Amitābha
      parent: Prayers
    82d64565320a4b34889ca46e706a7126:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Prayers
    5b15531c7157499396927e22fdb3e60e:
      title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
        Female Practice'
      parent: Sādhanas
created_at: '2022-02-28T22:58:39.861834'
last_modified_at: '2022-02-28T22:58:39.861838'
